export default [
    {
        id: '1',
        name: 'Somn pe pat de cartofi la cuptor',
        ingredients: [
            '2 bucati de pana de somn',
            '2 cartofi mari',
            '30 ml de vin alb sec',
            '3 fire de usturoi verde',
            '1 lingurita de unt',
            'sare piper'],
        recepee: [
            'Prima data asezam cartofii in tava pe care o vom pune la cuptor.',
            'Asezam pe fundul tavii un pat de cartofi, eu i-am taiat rondele. Presaram deasupra cu sare si piper.',
            'Saram si bucatile de peste, punem de doua ori sare cat luam cu doua degete si piper cat luam cu trei degete.',
            'Asezam pestele peste cartofi, iar deasupra presaram usturoiul verde, punem putin si sub bucatile de peste.',
            'Turnam vinul in tava. Untul il punem deasupra bucatilor de peste.',
            'Puntem tava la cuptor, la o temperatura de 200-220 de grade Celsius, la cuptoarele electric, foc mediu spre maxim, la cuptoarele pe gaz.',
            'Coacerea dureaza in jur de 30 de minute. In primele 15 minute e bine sa acoperim pestele cu folie de aluminiu (sau sa acoperim tava cu un capac), astfel incat pestele si legumele sa se gateasca inabusit. Dupa acest timp scoatem folia si lasam totul sa rumeneasca.',
            'Cand somnul s-a rumenit frumos si legumele sunt bine patrunse, putem servi friptura.'],
        img: '/images/retete/01.jpg',
        time: 45,
    },
    {
        id: '2',
        name: 'Somn pe pat de cartofi la cuptor',
        ingredients: [
            '2 bucati de pana de somn',
            '2 cartofi mari',
            '30 ml de vin alb sec',
            '3 fire de usturoi verde',
            '1 lingurita de unt',
            'sare piper'],
        recepee: [
            'Prima data asezam cartofii in tava pe care o vom pune la cuptor.',
            'Asezam pe fundul tavii un pat de cartofi, eu i-am taiat rondele. Presaram deasupra cu sare si piper.',
            'Saram si bucatile de peste, punem de doua ori sare cat luam cu doua degete si piper cat luam cu trei degete.',
            'Asezam pestele peste cartofi, iar deasupra presaram usturoiul verde, punem putin si sub bucatile de peste.',
            'Turnam vinul in tava. Untul il punem deasupra bucatilor de peste.',
            'Puntem tava la cuptor, la o temperatura de 200-220 de grade Celsius, la cuptoarele electric, foc mediu spre maxim, la cuptoarele pe gaz.',
            'Coacerea dureaza in jur de 30 de minute. In primele 15 minute e bine sa acoperim pestele cu folie de aluminiu (sau sa acoperim tava cu un capac), astfel incat pestele si legumele sa se gateasca inabusit. Dupa acest timp scoatem folia si lasam totul sa rumeneasca.',
            'Cand somnul s-a rumenit frumos si legumele sunt bine patrunse, putem servi friptura.'],
        img: '/images/retete/01.jpg',
        time: 45,
    },
    {
        id: '3',
        name: 'Somn pe pat de cartofi la cuptor',
        ingredients: [
            '2 bucati de pana de somn',
            '2 cartofi mari',
            '30 ml de vin alb sec',
            '3 fire de usturoi verde',
            '1 lingurita de unt',
            'sare piper'],
        recepee: [
            'Prima data asezam cartofii in tava pe care o vom pune la cuptor.',
            'Asezam pe fundul tavii un pat de cartofi, eu i-am taiat rondele. Presaram deasupra cu sare si piper.',
            'Saram si bucatile de peste, punem de doua ori sare cat luam cu doua degete si piper cat luam cu trei degete.',
            'Asezam pestele peste cartofi, iar deasupra presaram usturoiul verde, punem putin si sub bucatile de peste.',
            'Turnam vinul in tava. Untul il punem deasupra bucatilor de peste.',
            'Puntem tava la cuptor, la o temperatura de 200-220 de grade Celsius, la cuptoarele electric, foc mediu spre maxim, la cuptoarele pe gaz.',
            'Coacerea dureaza in jur de 30 de minute. In primele 15 minute e bine sa acoperim pestele cu folie de aluminiu (sau sa acoperim tava cu un capac), astfel incat pestele si legumele sa se gateasca inabusit. Dupa acest timp scoatem folia si lasam totul sa rumeneasca.',
            'Cand somnul s-a rumenit frumos si legumele sunt bine patrunse, putem servi friptura.'],
        img: '/images/retete/01.jpg',
        time: 45,
    },
    {
        id: '4',
        name: 'Somn pe pat de cartofi la cuptor',
        ingredients: [
            '2 bucati de pana de somn',
            '2 cartofi mari',
            '30 ml de vin alb sec',
            '3 fire de usturoi verde',
            '1 lingurita de unt',
            'sare piper'],
        recepee: [
            'Prima data asezam cartofii in tava pe care o vom pune la cuptor.',
            'Asezam pe fundul tavii un pat de cartofi, eu i-am taiat rondele. Presaram deasupra cu sare si piper.',
            'Saram si bucatile de peste, punem de doua ori sare cat luam cu doua degete si piper cat luam cu trei degete.',
            'Asezam pestele peste cartofi, iar deasupra presaram usturoiul verde, punem putin si sub bucatile de peste.',
            'Turnam vinul in tava. Untul il punem deasupra bucatilor de peste.',
            'Puntem tava la cuptor, la o temperatura de 200-220 de grade Celsius, la cuptoarele electric, foc mediu spre maxim, la cuptoarele pe gaz.',
            'Coacerea dureaza in jur de 30 de minute. In primele 15 minute e bine sa acoperim pestele cu folie de aluminiu (sau sa acoperim tava cu un capac), astfel incat pestele si legumele sa se gateasca inabusit. Dupa acest timp scoatem folia si lasam totul sa rumeneasca.',
            'Cand somnul s-a rumenit frumos si legumele sunt bine patrunse, putem servi friptura.'],
        img: '/images/retete/01.jpg',
        time: 45,
    },
    {
        id: '5',
        name: 'Somn pe pat de cartofi la cuptor',
        ingredients: [
            '2 bucati de pana de somn',
            '2 cartofi mari',
            '30 ml de vin alb sec',
            '3 fire de usturoi verde',
            '1 lingurita de unt',
            'sare piper'],
        recepee: [
            'Prima data asezam cartofii in tava pe care o vom pune la cuptor.',
            'Asezam pe fundul tavii un pat de cartofi, eu i-am taiat rondele. Presaram deasupra cu sare si piper.',
            'Saram si bucatile de peste, punem de doua ori sare cat luam cu doua degete si piper cat luam cu trei degete.',
            'Asezam pestele peste cartofi, iar deasupra presaram usturoiul verde, punem putin si sub bucatile de peste.',
            'Turnam vinul in tava. Untul il punem deasupra bucatilor de peste.',
            'Puntem tava la cuptor, la o temperatura de 200-220 de grade Celsius, la cuptoarele electric, foc mediu spre maxim, la cuptoarele pe gaz.',
            'Coacerea dureaza in jur de 30 de minute. In primele 15 minute e bine sa acoperim pestele cu folie de aluminiu (sau sa acoperim tava cu un capac), astfel incat pestele si legumele sa se gateasca inabusit. Dupa acest timp scoatem folia si lasam totul sa rumeneasca.',
            'Cand somnul s-a rumenit frumos si legumele sunt bine patrunse, putem servi friptura.'],
        img: '/images/retete/01.jpg',
        time: 45,
    },
    {
        id: '6',
        name: 'Somn pe pat de cartofi la cuptor',
        ingredients: [
            '2 bucati de pana de somn',
            '2 cartofi mari',
            '30 ml de vin alb sec',
            '3 fire de usturoi verde',
            '1 lingurita de unt',
            'sare piper'],
        recepee: [
            'Prima data asezam cartofii in tava pe care o vom pune la cuptor.',
            'Asezam pe fundul tavii un pat de cartofi, eu i-am taiat rondele. Presaram deasupra cu sare si piper.',
            'Saram si bucatile de peste, punem de doua ori sare cat luam cu doua degete si piper cat luam cu trei degete.',
            'Asezam pestele peste cartofi, iar deasupra presaram usturoiul verde, punem putin si sub bucatile de peste.',
            'Turnam vinul in tava. Untul il punem deasupra bucatilor de peste.',
            'Puntem tava la cuptor, la o temperatura de 200-220 de grade Celsius, la cuptoarele electric, foc mediu spre maxim, la cuptoarele pe gaz.',
            'Coacerea dureaza in jur de 30 de minute. In primele 15 minute e bine sa acoperim pestele cu folie de aluminiu (sau sa acoperim tava cu un capac), astfel incat pestele si legumele sa se gateasca inabusit. Dupa acest timp scoatem folia si lasam totul sa rumeneasca.',
            'Cand somnul s-a rumenit frumos si legumele sunt bine patrunse, putem servi friptura.'],
        img: '/images/retete/01.jpg',
        time: 45,
    },
]