export default [
    {
        id: '1',
        name: 'Somn la tigaie',
        ingredients: [
            '1 somn (cca 1,5 kg)',
            '3-4 linguri faina',
            'ulei pentru prajit',
            'sare'],
        recepee: [
            'Evisceram pestele si il spalam. Il taiem in bucati mai mici si il dam cu sare.',
            'Dam fiecare bucata de peste prin faina.',
            'Prajim bucatile de peste in uleiul incins pana se rumenesc.',
            'Scoatem pestele pe servetele absorbante pentru a elimina excesul de ulei.',
            'Servim cu mamaliguta calda si dupa gust il putem asezona cu zeama de lamaie.',
            ],
        img: '/images/retete/02.jpg',
        time: 20,
    },
    {
        id: '2',
        name: 'Somn pe pat de cartofi la cuptor',
        ingredients: [
            '2 bucati de pana de somn',
            '2 cartofi mari',
            '30 ml de vin alb sec',
            '3 fire de usturoi verde',
            '1 lingurita de unt',
            'sare piper'],
        recepee: [
            'Prima data asezam cartofii in tava pe care o vom pune la cuptor.',
            'Asezam pe fundul tavii un pat de cartofi, eu i-am taiat rondele. Presaram deasupra cu sare si piper.',
            'Saram si bucatile de peste, punem de doua ori sare cat luam cu doua degete si piper cat luam cu trei degete.',
            'Asezam pestele peste cartofi, iar deasupra presaram usturoiul verde, punem putin si sub bucatile de peste.',
            'Turnam vinul in tava. Untul il punem deasupra bucatilor de peste.',
            'Puntem tava la cuptor, la o temperatura de 200-220 de grade Celsius, la cuptoarele electric, foc mediu spre maxim, la cuptoarele pe gaz.',
            'Coacerea dureaza in jur de 30 de minute. In primele 15 minute e bine sa acoperim pestele cu folie de aluminiu (sau sa acoperim tava cu un capac), astfel incat pestele si legumele sa se gateasca inabusit. Dupa acest timp scoatem folia si lasam totul sa rumeneasca.',
            'Cand somnul s-a rumenit frumos si legumele sunt bine patrunse, putem servi friptura.'],
        img: '/images/retete/01.jpg',
        time: 45,
    },
    {
        id: '3',
        name: 'Spaghete bolognese cu somn',
        ingredients: [
            '500 g file de somn',
            '½ ceapa rosie',
            '500 g sos de rosii',
            'oregano',
            'busuioc',
            'sare, piper',
            'ulei de masline',
            '400 g de spaghete',
            '200 g cascaval',
            'busuioc proaspăt pentru servire',
        ],
        recepee: [
            'Măcinăm fileul de somn într-o mașină de tocat carne.',
            'Se călește ceapa în ulei de masline, apoi se adauga peștele tocat și se fierbe până ce peștele își elibereaza zeama si se caleste si el.',
            'Punem sosul de roșii cu condimentele și fierbem totul.',
            'Între timp, fierbeți pastele în apă cu sare, strecurați-le și amestecați-le cu o lingură de sos bolognez, pentru ca pastele să nu se lipească și culoarea să fie mai frumoasă.',
            'La servire, punem sos bolognez de somn peste paste, stropim cu cașcava ras și decorăm cu frunze de busuioc proaspăt.',
            ],
        img: '/images/retete/03.jpg',
        time: 30,
    },
    {
        id: '4',
        name: 'Papricas de somn cu paste',
        ingredients: [
            '1,2 kg file de somn',
            '4 cepe',
            '200 g bacon afumat',
            '1 lingura boia de ardei',
            'sare, piper',
            '1 lingurita chimen macinat',
            '2 catei de usturoi',
            '100 ml smantana',
            '1 lingura de faina',
            '1 rosie',
            '1 ardei (nu picant)',
            '150 g paste',
            'ulei',
            ],
        recepee: [
            'Tăiați somnul în cuburi de 3x3 cm și lăsați-l să stea puțin în sare.',
            'Tăiați slănina afumată în felii, adăugați feliile in ulei și prăjiți-le.',
            'Scoateți slănina din tigaie și prăjiți ceapa tocată în grăsimea rămasă din slănină până devine sticloasă.',
            'Se adauga boia, ardeiul si rosiile tocate, apoi se toarna putina apa.',
            'Se fierbe baza timp de 1 ora, apoi se adauga faina amestecata in smantana.',
            'Dupa cateva minute adaugam si bucatile de peste si fierbem 10 minute',
            'Servim cu pasta fiarta',
            ],
        img: '/images/retete/04.jpg',
        time: 90,
    },
    {
        id: '5',
        name: 'Rulouri cu somn',
        ingredients: [
            'Crema de branza',
            '200 g Somn',
            '100 g Iaurt grecesc',
            '100 g Castraveti murati',
            '200 g Porumb',
            'Marar',
            'Sare',
            'Piper',
            '1 lingura Zeama de lamaie',
            '6 bucati Lipii de tortilla',
        ],
        recepee: [
            'Toaca marunt somnul, castraveciorii, mararul.',
            'Scurge foarte bine porumbul din conserva.',
            'Amesteca foarte bine toate ingredientele, adaugand iaurt grecesc pana ai o crema tartinabila.',
            'Imparte crema in 6 parti egale, unge uniform fiecare tortilla, ruleaza strans.',
            'Este ideal sa lasi rulourile la rece 30 de minute inainte de feliere, pentru a-si pastra bine forma.',
            'Reteta de Rulouri cu somon este gata. Se pastreaza foarte bine 2 zile la frigider, deci le poti pregati din timp pentru petreceri sau pentru ziua urmatoare pentru pranz.',
            ],
        img: '/images/retete/05.jpg',
        time: 30,
    },
    {
        id: '6',
        name: 'Chiftelute din somn',
        ingredients: [
            '1 kg carne tocata de somn(partea de la coada si burta',
            'o legatura mare de marar verde',
            '2 -3 oua',
            'un praf de sare',
            'piper',
            '6-7 catei de usturoi',
            '3-4 felii de paine veche',
            'ulei pentru prajit'    ,
        ],
        recepee: [
            'Se scoate carnea de pe os cu un cutit ascutit,apoi se da de 2 ori prin masina de tocat cu sita marunta.',
            'Painea veche se inmoaie in apa rece apoi se preseaza in maini pana eliminam pe cat posibil apa.',
            'Mararul se taie marunt,usturoiul curatat se zdrobeste bine.',
            'Se amesteca carnea tocata de peste cu toate ingredientele, apoi se sareaza si condimenteaza dupa gust.',
            'Cu mainile umezite in apa rece ,modelam chiftelute care se prajesc in ulei incins apoi se scot pe servetele absorbante pentru a scapa de surplusul de ulei. Sunt delicioase calde dar si reci.',
            ],
        img: '/images/retete/06.jpg',
        time: 30,
    },
]